erDiagram
    %% Laravel ERD Diagram

    User {
        bigint id PK
        string name
        string email
        string password
        string active
        timestamp created_at
        timestamp updated_at
    }

    TradeTerm {
        bigint id PK
        boolean active
        timestamp created_at
        timestamp updated_at
    }

    State {
        bigint id PK
        timestamp created_at
        timestamp updated_at
    }

    Staff {
        bigint id PK
        boolean active
        timestamp created_at
        timestamp updated_at
    }

    ShippingAddress {
        bigint id PK
        boolean active
        timestamp created_at
        timestamp updated_at
    }

    PaymentTerm {
        bigint id PK
        boolean active
        timestamp created_at
        timestamp updated_at
    }

    Factory {
        bigint id PK
        string name_english
        string name_china
        string phone_1
        string phone_2
        string email
        string website
        string address_to
        string address_street1
        string address_street2
        string city_id
        string state_id
        string country_id
        string address_postcode
        boolean active
        timestamp created_at
        timestamp updated_at
    }

    CustomerEmail {
        bigint id PK
        string customer_id
        string name
        string email
        timestamp created_at
        timestamp updated_at
    }

    Customer {
        bigint id PK
        boolean active
        timestamp created_at
        timestamp updated_at
    }

    Country {
        bigint id PK
        timestamp created_at
        timestamp updated_at
    }

    City {
        bigint id PK
        timestamp created_at
        timestamp updated_at
    }

    ShippingAddress ||--|| Factory : "belongs to"
